server:
  port: 9192

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JK_NANA_SHOP
    username: jon
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Correct way to format SQL output

  # Enable Transactional Logging (Optional)
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Correcting the API Prefix Setting
api:
  prefix: /api/v1
