spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/JK_NANA_SHOP
    username: jon
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false  # Disable auto-commit for handling Large Objects

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true  # Helps with LOB handling in Hibernate

server:
  port: 9192

api:
  prefix: /api/v1
